ropensci/ckanr

tests/testthat/test-organization_list.R
tests/testthat/test-organization_show.R

The data in the "http://demo.cakn.org" is growing, so we need to match the number from the web page and the API from ckanr.

check the number based on webpage

---

DESCRIPTION

The httr::content will try XML to parse the html formatted response. Therefore, I suggest to put the XML into Suggests. We could parse the response and compare with our API in the unit test.

add XML to Suggests

---

R/ckanr_options.R
R/ds_create_dataset.R
R/resource_update.R
man/ckanr_options.Rd
man/set_test_env.Rd
tests/testthat/test-ds_create_dataset.R
tests/testthat/test-resource_update.R

This PR addresses #30 
Tests like `test-resource_update.R` require write access to a CKAN instance. At least a URL, an API key, an existing dataset ID and an existing resource ID (attached to dataset ID) must be given. Testthat apparently can't access options(), but can get to Sys.env.
`ckan_options.R`: `set_test_env()` now writes test server settings to both options (so `ckanr_options()` can print them) and Sys.env.
The "non-readonly" tests pass when run with `test_file("tests/testthat/test-{resource_update, ds_create_dataset}.R")` but skip when run with devtools::test().
devtools::check() runs successfully with 1 (unrelated) warning about `print.ckanr_options`.
Running the "non-readonly" test requires:
```{R}
set_test_env("http://my.test.ckan.org/",
"my-test-ckan-api-key", …
```

Using Sys.env to store test server settings

---

R/ds_create_dataset.R
R/package_show.R
R/resource_show.R
R/resource_update.R
man-roxygen/key.R
man/ds_create.Rd
man/ds_create_dataset.Rd
man/package_show.Rd
man/resource_show.Rd
man/resource_update.Rd

addressing #34 
Thanks to `@template args`, `url`, `as` and `...` are already documented. Streamlined api key docstring into `@template key` and did some reformatting (hope that's ok).
Edit: I don't fully understand how coveralls finds that this PR reduces the test coveage by 10%.

solves #34 removed unused argument "key" from package_show and resource_show

---

R/tag_show.R
man/tag_show.Rd
tests/testthat/test-tag_show.R

Addressing #41 tests pass again with Travis's test server settings (data-demo.dpaw.wa.gov.au).

added parameter include_datasets=FALSE to tag_show to match CKAN API

---

R/resource_update.R

Fix #64 
This PR adds a handful of resource formats to `resource_update`'s lookup helper, covering my use cases. 
This PR will primarily serve users who use `ckanr` to grab data from CKAN, produce some data products (figures as png/jpeg/png/pdf, data as csv/xlsx) and finally want to upload the products (and why not the code as text / RMarkdown workbook as html output while we're at it) back to a CKAN dataset.
More formats to be added:
* formats supported by CKAN previews (some MS office formats might be missing)
* [custom mimetypes](http://docs.ckan.org/en/latest/maintaining/filestore.html#custom-internet-media-types-mime-types) defined in CKAN extensions
* ckanext-ecportal's [mime types](https://github.com/okfn/ckanext-ecportal/blob/master/data/resource_mapping.json) and [dropdown …

fix #64 by adding resource formats

---

R/ds_create.R

This pull request brings the ds_create method to the point where it can insert records in the datastore resource.
@sckott I may have the chance to work a lot with this at the moment and would be up for filling in the gaps in and documenting the Datastore API. As I am not an R expert it might help me a lot if we could talk for 15m sometime to get a crash course on HTTP calls in R, package conventions, etc.

Update ds_create method to properly format body with json data

---

DESCRIPTION
R/ckan_fetch.R
R/zzz.R
codemeta.json
man/ckan_fetch.Rd

A few changes to the functionality of `ckan_fetch()` and the functions it depends on:
* Uses `sf::st_read()` instead of the deprecated`maptools::readShapePoints()`, closes #114 
* Updated examples in `ckan_fetch()` due to `http://publicdata.eu/` moving -- have changed them to some very 🇨🇦 centric ones!
* Allows reading and parsings of `xlsx` files (in addition to `xls` files already supported)
* (Some whitespace changes that just happen as a result of saving the file in RStudio -- not nitpicking your spaces!)
for the `xlsx` change, e.g. `ckan_fetch()` would return nothing with the current version of`ckanr` but works fine with the PR'd version:
``` r
library(ckanr)
#> Loading required package: DBI
ckanr_setup("https://ckan0.cf.opendata.inter.sandbox-toronto.ca")
res <- resource_show(id = …
```

Updates to ckan_fetch() and examples

---

R/ckan_fetch.R
R/zzz.R
man/ckan_fetch.Rd

Adds an additional (optional) `format` parameter to `ckan_fetch()` so that downloading can succeed even if the resource URL doesn't have the format in its extension; closes #116. I also started a test file for `ckan_fetch()`, starting with ensuring that the error works as expected.
Some examples:
``` r
library(ckanr)
#> Loading required package: DBI
ckanr_setup("https://data.europa.eu/euodp/data/")
res <- resource_show(id = "f2cfb3f8-44f6-4027-952f-a1d759484501", as = "table")
ckan_fetch(res$url)
#> Error in ckan_fetch(res$url): File format is not available from URL; please specify via `format` argument.
ckan_fetch(res$url, format = res$format)
#> {xml_document}
#> <html lang="en" dir="ltr" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/terms/" …
```

Add optional format argument to ckan_fetch()

---

tests/testthat/test-ckan_fetch.R

Add a test for the changes in #117, ensuring that the error works as expected when the format can't be parsed from the URL.

Add test for ckan_fetch()

---

R/as-ckan_package.R

Include API Key During Call to Package Show (resolves #122)
I updated the `get_package` call to explicitly pass along the API Key using `get_default_key`.
fix #122

fix: #122 include key during call to package_show

---

R/ckan_fetch.R
R/zzz.R

Closes #125 -- `ckan_fetch()` writes to `tempdir()` and then deletes the files written after.

ckan_fetch writes to tempdir() instead of working directory

---

tests/testthat/test-ckan_fetch.R

Tests for #128 -- ensures that `ckan_fetch()` doesn't add any files to the working directory, nor to `tempdir()`, once it's done.

Tests for ckan_fetch() writing to tempdir

---

.github/issue_template.md

Minor update to the standard issue template. In the long run, should `ckanr` use separate issue templates as per https://help.github.com/en/articles/about-issue-and-pull-request-templates? Happy to send PR.
Included a code block for the `traceback()` and explanatory comments to the details section.
@sckott had to remind me of the traceback() in #122 - let's push that onus to the issue template. 
Minor change, no code touched, no tests added.

Include traceback in standard issue template

---

R/ckan_fetch.R
R/zzz.R

The current treatment of `zip` files in `ckan_fetch()` only handles if they contain`shp` files, but it's possible for resources to have a zip files of other, non-shp files, that would need to be read in (the example added is [this](https://portal0.cf.opendata.inter.sandbox-toronto.ca/dataset/annual-summary-of-reportable-communicable-diseases/)). 
This PR checks if, unzipped, the resource contains `shp` files -- if so, the current method is used. If not, then it reads each file in separately and returns the result in a list, where the name is the name of the file in the zip.
The change to the `read.csv()` encoding is because i specifically ran into a file where it was an issue; let me know if you would prefer this in a different PR (or if there's a different encoding approach i should …

Update ckan_fetch() to handle non-SHP zip files

---

R/ckan_fetch.R
R/zzz.R
man/ckan_fetch.Rd

I think this is what's needed to add the API key header to `ckan_fetch()` as in @jonocarroll's comment in #122. I don't have access to a CKAN instance that needs an API key, so let me know if i'm off. thanks!

Add API key header to ckan_fetch

---

R/ckan_fetch.R

the Toronto Open Data CKAN url (and hence resource IDs) changed so I had to update the examples used in `ckan_fetch()`. thanks!

Update ckan_fetch examples based on CKAN url change

---

R/ckan_fetch.R
man/ckan_fetch.Rd

Currently `ckan_fetch()` only reads the first sheet of an `xls` / `xlsx` resource -- this PR implements a change so that it reads all of them and returns the result as a named list.
Also, apparently I forgot to update the documentation for #134 and #132 🙈 my bad!

Handle fetch of xls/xlsx resources with multiple sheets

---

R/ckan_info.R
man/ckan_info.Rd
tests/testthat/test-ckan_info.R

The current implementation of `ckan_version()` doesn't properly handle patch or dev versions, e.g. `2.2.1` gets converted to `221` instead of e.g. `22.1`, which causes issues downstream (i.e., in `package_search()`).
This implementation parses patch and dev versions too, e.g. `2.1.1` becomes `21.1`, `2.1` is `21`, `2.1.0` is `21`, etc.
Also added tests and set the default value of `url` to `get_default_url()` (that's what the documentation states it is, but it looks like it may have been missed). thanks!

Parse CKAN version number including patch/dev versions

---

R/package_search.R
man/package_search.Rd

as i said in #136, it looks like the ckan version logic used in `package_search()` is a little off. using the version of code in that PR:
``` r
library(ckanr)
ckan_version("http://data.techno-science.ca/")
#> $version
#> [1] "2.2"
#> 
#> $version_num
#> [1] 22
package_search(url = "http://data.techno-science.ca/", rows = 0)
#> $count
#> [1] 36
#> 
#> $sort
#> [1] "score desc, metadata_modified desc"
#> 
#> $facets
#> named list()
#> 
#> $results
#> list()
#> 
#> $search_facets
#> named list()
ckan_version("http://datamx.io")
#> $version
#> [1] "2.2.1b"
#> 
#> $version_num
#> [1] 22.1
package_search(url = "http://datamx.io", rows = 0)
#> $count
#> [1] 9659
#> 
#> $sort
#> [1] "score desc, metadata_modified desc"
#> 
#> $facets
#> named list()
#> 
#> $results
#> list()
#> 
#> $search_facets …
```

Change default_schema and include_private parameter availability logic in package_search

---

R/package_search.R
man/package_search.Rd

Sometimes the CKAN version isn't available via `api/util/status` so `package_search()` currently fails:
``` r
library(ckanr)
package_search(url = "http://data.go.id")
#> Error in ckan_info(url, ...): Not Found (HTTP 404).
package_search(url = "http://data.london.gov.uk")
#> Error in ckan_info(url, ...): Not Found (HTTP 404).
package_search(url = "https://ckan0.cf.opendata.inter.prod-toronto.ca")
#> Error in ckan_info(url, ...): Forbidden (HTTP 403).
```
the implementation in this PR treats the version as unknown (and therefore maybe < 2.3.5) so sets `include_drafts`, `use_default_schema`, and `include_private` as `NULL` so the functions doesn't fail (because we don't know if those params are available):
``` r
library(ckanr)
#> Loading required package: DBI
package_search(url = …
```

Handle case where CKAN version isn't available

---

R/ckan_fetch.R

Using `basename()` to get the file names for ZIP resources is way more robust than `gsub(paste0(tempdir(` etc, i.e. it actually works on Windows.
compare master
``` r
library(ckanr)
ckanr_setup("https://ckan0.cf.opendata.inter.prod-toronto.ca")
res <- resource_show(id = "bb21e1b8-a466-41c6-8bc3-3c362cb1ed55", as = "table")
x <- ckan_fetch(res$url)
names(x)
#> [1] "C:\\Users\\shg\\AppData\\Local\\Temp\\RtmpQpCyuY/ChickenpoxAgegroups2017.csv"             
#> [2] "C:\\Users\\shg\\AppData\\Local\\Temp\\RtmpQpCyuY/DiseaseSexandAgegroups2017.csv"          
#> [3] "C:\\Users\\shg\\AppData\\Local\\Temp\\RtmpQpCyuY/MeansbyDiseaseSex2007_2016.csv"          
#> [4] "C:\\Users\\shg\\AppData\\Local\\Temp\\RtmpQpCyuY/RatesbyDisease2007_2017.csv"             
#> [5] …
```

Use basename() for filenames

---

R/package_create.R
R/package_patch.R
R/package_show.R
R/resource_create.R
R/resource_show.R
man/package_create.Rd

On one of our internal CKAN instances, we have private datasets that do not behave properly upon attempts to `_show` or `_patch` them, even when the key is supplied. 
```r
library(ckanr)
key <- "XXXXX"
package_search("my_package", url="https://some_ckan_location.com", key=key)
```
Some detective work suggests that the `as.ckan_package()` is trying to convert character strings into package objects but lacks the authorization to do so as the `key` is not passed.
Pass the `key` to `as.ckan_package()`. I have only done this for the subset of functions that I actually needed for my day-to-day work, but it seems that it would be necessary for all functions.
Incidentally, I also took the liberty of adding a `private=` argument to `package_create()` so that I could easily create private packages. …

Minor fixes for private datasets

---

R/resource_create.R
R/resource_patch.R
R/resource_update.R
tests/testthat/test-resource_update.R

This PR adds support for resource-level extras to the `resource_create` method.
This adds the `extras` parameter to the `resource_create` method to allow adding arbitrary key:value pairs to ckan resources within a data package.
#149 
The change allows the following
```R
foo <- resource_create(
package_id = 'test-70mb', 
name = 'foo-6', 
extras = list(foo='bar', bar='baz'))
```
* verify extras are added

Add Support for Resources Extras 

---

R/package_patch.R
R/package_update.R
R/resource_create.R
man/package_patch.Rd
man/package_update.Rd
man/resource_create.Rd

Added the `http_method` parameter to `resource_create`, `package_update` and `package_patch`. The default is `http_method = GET`. - #109

Add http_method to resource_create, package_update and package_patch

---

R/ckan_fetch.R
R/zzz.R

Trying to close an opendatatoronto issue that I'm very delinquent on...  https://github.com/sharlagelfand/opendatatoronto/issues/10
Turns out it can happen that a ZIP resource contains a *subdirectory* that contains the actual files - when this is the case, `ckan_fetch()` fails because the subdirectory's format cannot be parsed - `file_fmt()` returns `character(0)` instead of `NA` (if it returned `NA`, then `switch()` in `read_session()` would handle it more gracefully, instead of the error below):
``` r
library(ckanr)
ckan_fetch("https://ckan0.cf.opendata.inter.prod-toronto.ca/download_resource/81ea3260-057a-4e62-ae45-1f40191a8229", format = "zip")
traceback()
```
This is the contents of the resource's directory once unzipped (extracted by manually stepping through `ckan_fetch()`):
``` r …
```

Return unknown file format as NA to handle ZIP resource with subdirectory

---

R/ckan_fetch.R
R/zzz.R
man/ckan_fetch.Rd

Updated `ckan_fetch()` to work with `txt` files (closes #160) - as we discussed in that issue, uses `read.table()` and errors if the txt file cannot be read via `read.table()`. Added an example into the docs too.
Just to look at when it works vs fails, using the examples from the linked issue:
``` r
library(ckanr)
head(ckan_fetch("https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/7b70189a-aede-42f1-b092-8708fa4f5fc3/resource/e4211f49-611f-438c-a444-aaa7f3f84117/download/pickup-schedule-2020.txt"))
```
``` r
library(ckanr)
ckan_fetch("https://ckan0.cf.opendata.inter.prod-toronto.ca/download_resource/c238eb23-474a-445f-8037-50d440502219", format = "txt")
```
I'm using the default `header = FALSE` in `read.table()` - I figure it's less of a pain to make one of the rows into the column …

Update ckan_fetch() to work with txt files

---

R/servers.R

Add Government of British Columbia, Canada https://catalogue.data.gov.bc.ca back into list of servers(). 
A version was removed as part of Issue #162 - http://catalogue.data.gov.bc.ca - however it works if https is used in URL.

Update servers.R add catalogue

---

R/resource_update.R
man/resource_update.Rd
tests/testthat/test-resource_update.R

This PR makes the `path` parameter to `resource_update` optional in order to support updating of resource extra fields.
While `resource_patch` ckan api allows for modifying the value of a given resource extra, it does not allow for deleting an extra that is no longer needed. (note that extras are not supported in the `ckanr::resource_patch`)
The current behavior only supports `resource_update` when a the file/url is being uploaded which may require an unnecessary download and reupload of a file just to remove a metadata field.
Todos
```
id <- resource_update(id$id, extras = list(foo='bar'))
resource_update(id)
```

Support updating of resource extra fields w/o including a path parameter

---

.Rbuildignore
.github/CONTRIBUTING.md
ckanr.Rproj
docker-compose.yml
tests/test-all.R
tests/testthat/helper-ckanr.R
tests/testthat/test-ckan_fetch.R
tests/testthat/test-resource_show.R
tests/testthat/test-tag_search.R

- Add `docker-compose.yml` to spin-up a local CKAN site at `localhost:5000/ `
- Add basic instructions for how to launch the docker containers in the contribution guidelines
- Switch all testing using `demo.ckan.org/` and `datamx.io/` to `localhost:5000/` and make sure they pass
- Move `prepare_test_ckan()` from `tests/test-all.R` to `tests/testthat/helper-ckanr.R`
See ropensci/ckanr#182 for the potential problems in testing against external CKAN sites.

Add docker compose setup for local testing

---

.github/CONTRIBUTING.md
.github/workflows/R-check.yaml
docker-compose.yml
tests/testthat/helper-ckanr.R
tests/testthat/test-changes.R
tests/testthat/test-ckan_fetch.R
tests/testthat/test-group_show.R
tests/testthat/test-license_list.R
tests/testthat/test-organization_list.R
tests/testthat/test-package_activity_list.R
tests/testthat/test-ping.R
tests/testthat/test-tag_show.R

Closes #144 
- Adapt docker compose setup from #190 for use in Github Actions
- Test against CKAN versions 2.9, 2.8 and 2.7 following [CKAN maintenance cycle](https://github.com/ckan/ckan/issues/6787#issuecomment-1093095804)
Docker is not supported fully on Windows and MacOS runners, therefore the tests against CKAN are run only for ubuntu. Because of this I'm also generating code coverage and running r-devel against ubuntu.
The tricky part for me was discovering that by default docker compose sets up a single [network](https://docs.docker.com/engine/reference/commandline/network_create/). Each container joins the default network and is both _reachable_ by other containers on that network, and _discoverable_ by them at a hostname identical to the container name. However, the hostname of …

Spin-up CKAN for testing in Github Actions
